"""SQLite baslangic semasi

Revision ID: 41a96747a9b4
Revises:
Create Date: 2026-08-05 10:45:36.586355

Postgres'ten SQLite'a gecis nedeniyle onceki ~35 migration'lik gecmis
(Postgres'e ozel DDL: JSONB, `= ANY(:params)`, ve SQLite'in native
ALTER TABLE'inin desteklemedigi op.drop_column/op.alter_column/
op.drop_constraint dizileri) tek bir temiz baslangic semasina squash
edildi. `app/db/models.py` (Base.metadata) referans alinarak alembic
autogenerate ile uretildi - o an gecerli semayla BIREBIR aynidir. Eski
migration dosyalari (referans/tarihce icin) proje disinda saklanmaktadir;
gercek veri kaybi soz konusu degildir (bu degisiklik oncesinde production
veri yoktu).

Bu dosyaya ELLE eklenen tek sey, autogenerate'in dialect'e-ozel WHERE
kosullu index'leri (partial index) URETMEMESI nedeniyle
`uq_masking_runs_context_in_progress_mask` partial UNIQUE index'idir -
bkz. asagidaki op.create_index cagrisi ve app/services/exporter.py
_ensure_no_in_progress_run/export_project dokstring'leri.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41a96747a9b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dosya_tipi_kategori_kisitlamasi',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('dosya_uzantisi', sa.String(length=20), nullable=False, comment="Nokta olmadan, kucuk harf dosya uzantisi (orn. 'py', 'yaml')."),
    sa.Column('izinli_kategori', sa.String(length=100), nullable=False, comment="Bu uzanti icin izin verilen Presidio yerlesik entity_type'i (orn. 'EMAIL_ADDRESS')."),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False, comment='Pasif satirlar yeni taramalarda kullanilmaz.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dosya_uzantisi', 'izinli_kategori', name='uq_file_category_restriction'),
    comment="Dosya uzantisina gore Katman 2 Presidio'nun hangi yerlesik kategorileri calistiracagini kisitlayan veri-odakli tablo. Uzanti icin satir yoksa kisitlama yok."
    )
    op.create_table('filtre_kurallari',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('kural_adi', sa.String(length=100), nullable=False, comment='Kuralin benzersiz adi (orn. email_address, generic_secret_assignment).'),
    sa.Column('kategori', sa.String(length=50), nullable=False, comment='Parametrik kurallarda calisma-zamani parametre anahtari (orn. project_name); regex kurallarda sadece gruplama/etiket amaclidir.'),
    sa.Column('kaynak_katman', sa.String(length=50), nullable=False, comment="'katman1', 'katman2_presidio' ya da 'llm'. Ayni filtre_kurallari tablosunun hangi detector tarafindan okunacagini belirler."),
    sa.Column('desen_tipi', sa.String(length=20), nullable=False, comment="'regex' (sabit desen), 'parametric' (deger calisma zamaninda saglanir), 'llm' (yerel LLM ile taranan veri) ya da 'presidio' (Katman 2 Presidio pattern kuralı)."),
    sa.Column('regex_deseni', sa.Text(), nullable=True, comment="pattern_type='regex' icin aranacak regex; parametrik/llm kurallarda NULL. desen_sifreli_mi=True ise bu kolon duz metin regex DEGIL, Fernet ile sifrelenmis regex metnidir (bkz. app/core/crypto.py, app/repository/filter_rule_repository.py)."),
    sa.Column('desen_sifreli_mi', sa.Boolean(), nullable=False, comment="True ise regex_deseni duz metin degil, Fernet ile sifrelenmis regex metnidir - kurumsal terim sozlugu gibi, kendisi hassas olan kural kaynaklari icin kullanilir (bkz. app/services/term_upload.py). Okuyan taraf (filter_rule_repository.py) list_active_detection_rules()'ta bu bayragi gorup decrypt_value() cagirir."),
    sa.Column('regex_bayraklari', sa.String(length=10), nullable=True, comment="Regex bayraklari (orn. 'i' = buyuk/kucuk harf duyarsiz)."),
    sa.Column('dogrulayici_adi', sa.String(length=50), nullable=True, comment="Regex eslesmesinden sonra ek dogrulama (checksum vb.) yapan, app/services/validators.py icindeki adlandirilmis fonksiyon; sadece 'regex' tipi kurallarda kullanilir (orn. 'tc_kimlik_no')."),
    sa.Column('yer_tutucu_on_eki', sa.String(length=50), nullable=False, comment="Eslesen degerin yerine yazilacak placeholder'in on eki (orn. mask_email -> mask_email_1)."),
    sa.Column('entity_tipi', sa.String(length=100), nullable=True, comment='Katman 2 Presidio icin DetectionResult.tip/entity_type degeri (orn. IC_SERVIS_ADI).'),
    sa.Column('guven_skoru', sa.Float(), nullable=False, comment='Katman 2 Presidio PatternRecognizer skoru; DetectionResult guven seviyesine cevrilir.'),
    sa.Column('allow_list_mi', sa.Boolean(), nullable=False, comment="True ise bu regex hassas veri uretmez; ayni span'a dusen Katman 2 bulgularini bastirir."),
    sa.Column('oncelik', sa.Integer(), nullable=False, comment='Kurallarin uygulanma sirasi; dusuk sayi once calisir, cakismalari kazanir.'),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False, comment='Pasif kurallar yeni taramalarda kullanilmaz ama gecmis eslemeleri bozmaz.'),
    sa.Column('aciklama', sa.Text(), nullable=True, comment="Kuralin ne yaptigina dair serbest metin aciklama; pattern_type='llm' kurallarda bu alan ZORUNLUDUR ve gercekten LLM'e giden promptun bir parcasi olur (bkz. app/services/llm_recognizer.py _augment_prompt, app/services/mapping_service.py build_orchestrator)."),
    sa.CheckConstraint("(desen_tipi = 'regex' AND regex_deseni IS NOT NULL) OR (desen_tipi = 'parametric' AND regex_deseni IS NULL AND dogrulayici_adi IS NULL) OR (desen_tipi = 'llm' AND regex_deseni IS NULL AND dogrulayici_adi IS NULL AND aciklama IS NOT NULL) OR (desen_tipi = 'presidio' AND regex_deseni IS NOT NULL AND entity_tipi IS NOT NULL)", name='ck_filter_rules_regex_required_for_static'),
    sa.CheckConstraint("desen_tipi IN ('regex', 'parametric', 'llm', 'presidio')", name='ck_filter_rules_pattern_type'),
    sa.CheckConstraint("kaynak_katman IN ('katman1', 'katman2_presidio', 'llm')", name='ck_filter_rules_source_layer'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kural_adi'),
    comment='Katman 1, Katman 2 Presidio ve LLM kurallarini tek yerde tutan birlesik kural listesi. Yeni kural = yeni satir, kod degisikligi gerekmez.'
    )
    op.create_table('haric_tutma_desenleri',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('desen_adi', sa.String(length=100), nullable=False, comment='Deseninin benzersiz adi.'),
    sa.Column('glob_deseni', sa.String(length=200), nullable=False, comment="fnmatch uyumlu glob deseni (orn. '*.pem')."),
    sa.Column('uygulanir', sa.String(length=20), nullable=False, comment="'file', 'directory' ya da 'both' - desen dosyaya mi klasore mi uygulanir."),
    sa.Column('aktif_mi', sa.Boolean(), nullable=False, comment='Pasif desenler yeni taramalarda kullanilmaz.'),
    sa.CheckConstraint("uygulanir IN ('file', 'directory', 'both')", name='ck_exclude_patterns_applies_to'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('desen_adi'),
    comment='Icerigi hic taranmadan, sadece dosya/klasor adina gore (glob deseni) tamamen disarida birakilacak dosya turleri (orn. .env, .git, *.pem).'
    )
    op.create_table('maskeleme_baglamlari',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('proje_adi', sa.String(length=200), nullable=False, comment='Maskelenen projenin adi.'),
    sa.Column('personel_no', sa.String(length=50), nullable=False, comment='Islemi baslatan personelin numarasi.'),
    sa.Column('branch_adi', sa.String(length=200), nullable=False, comment='Ilgili git branch adi.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proje_adi', 'personel_no', 'branch_adi', name='uq_masking_context_identity'),
    comment="Proje + sicil + branch uclusunu temsil eden kimlik kaydi; her eslesmenin ve placeholder sayacinin hangi 'baglama' ait oldugunu belirler."
    )
    op.create_table('yer_tutucu_sayaclari',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('on_ek', sa.String(length=50), nullable=False, comment="Placeholder oneki (orn. 'mask_email') - filtre_kurallari.yer_tutucu_on_eki ile ayni degerler."),
    sa.Column('sayac', sa.Integer(), nullable=False, comment='Bu onek icin en son atanan global sayac degeri.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('on_ek')
    )
    op.create_table('deger_eslemeleri',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('baglam_id', sa.Integer(), nullable=False, comment='Ait oldugu maskeleme_baglamlari kaydi.'),
    sa.Column('kural_id', sa.Integer(), nullable=True, comment='Eslesmeyi ureten kural.'),
    sa.Column('orijinal_deger_sifreli', sa.Text(), nullable=False, comment='Orijinal hassas degerin sifreli hali.'),
    sa.Column('orijinal_deger_hash', sa.String(length=64), nullable=False, comment='Ayni degerin tekrar maskelenip maskelenmedigini tespit etmek icin kullanilan hash.'),
    sa.Column('yer_tutucu_degeri', sa.String(length=150), nullable=False, comment='Metinde orijinal degerin yerine yazilan placeholder (orn. mask_email_1).'),
    sa.ForeignKeyConstraint(['baglam_id'], ['maskeleme_baglamlari.id'], ),
    sa.ForeignKeyConstraint(['kural_id'], ['filtre_kurallari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baglam_id', 'orijinal_deger_hash', name='uq_mapping_context_original'),
    sa.UniqueConstraint('baglam_id', 'yer_tutucu_degeri', name='uq_mapping_context_placeholder'),
    comment="Orijinal deger <-> placeholder eslemesinin kalici kaydi. Sistemin 'hafizasi' - geri donusturulebilir (unmask) olmanin temeli."
    )
    op.create_table('maskeleme_calismalari',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('baglam_id', sa.Integer(), nullable=False, comment='Ait oldugu maskeleme_baglamlari kaydi.'),
    sa.Column('islem_tipi', sa.String(length=20), nullable=False, comment="'mask' ya da 'unmask'."),
    sa.Column('kaynak_yol', sa.Text(), nullable=False, comment='Okunan (hic degistirilmeyen) kaynak klasor yolu.'),
    sa.Column('hedef_yol', sa.Text(), nullable=True, comment='Sonucun yazildigi hedef klasor yolu.'),
    sa.Column('baslatan', sa.String(length=50), nullable=False, comment='Calismayi baslatan personelin numarasi.'),
    sa.Column('durum', sa.String(length=30), nullable=False, comment="'in_progress', 'completed' ya da 'completed_with_warnings'. NOT: bir calisma exception ile basarisiz olursa bu satirin TAMAMI rollback edilir (bkz. exporter.py/unmasker.py except bloklari) - yani basarisiz bir run DB'de HICBIR IZ birakmaz, 'failed' diye bir durum deger burada hic olusmaz (kasitli, bkz. proje DB semasi sadelestirme notlari)."),
    sa.Column('baslangic_tarihi', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Calismanin baslama zamani.'),
    sa.Column('bitis_tarihi', sa.DateTime(timezone=True), nullable=True, comment='Calismanin bitis zamani.'),
    sa.Column('dosya_sayisi', sa.Integer(), nullable=True, comment='Bu calismada taranan toplam dosya sayisi (rapor tamamlaninca doldurulur).'),
    sa.Column('bulgu_sayisi', sa.Integer(), nullable=True, comment='mask icin toplam eslesme, unmask icin toplam bulunan placeholder sayisi.'),
    sa.CheckConstraint("durum IN ('in_progress', 'completed', 'completed_with_warnings')", name='ck_masking_runs_status'),
    sa.CheckConstraint("islem_tipi IN ('mask', 'unmask')", name='ck_masking_runs_operation_type'),
    sa.ForeignKeyConstraint(['baglam_id'], ['maskeleme_baglamlari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Her export (maskeleme) ya da unmask (geri donusum) calismasinin kaydi - ne zaman baslamis/bitmis, hangi durumda.'
    )
    op.create_table('denetim_kaydi',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('calisma_id', sa.Integer(), nullable=False, comment='Ait oldugu maskeleme_calismalari kaydi.'),
    sa.Column('dosya_yolu', sa.Text(), nullable=False, comment='Olayin gerceklestigi dosyanin goreli yolu.'),
    sa.Column('eylem', sa.String(length=20), nullable=False, comment="'matched', 'replaced', 'skipped', 'error', 'cakisma' (OverlapResolver'da kaybeden bulgu), 'sinir_ihlali' (TokenBoundaryValidator'da reddedilen bulgu) ya da 'sozdizimi_hatasi' (post-export dogrulamasini gecemeyen, basarisiz_dosyalar/'a tasinan dosya)."),
    sa.Column('detay', sa.Text(), nullable=True, comment='Olayla ilgili serbest metin detay.'),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Olayin zamani.'),
    sa.CheckConstraint("eylem IN ('matched', 'replaced', 'skipped', 'error', 'cakisma', 'sinir_ihlali', 'sozdizimi_hatasi', 'round_trip_hatasi')", name='ck_audit_log_action'),
    sa.ForeignKeyConstraint(['calisma_id'], ['maskeleme_calismalari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Bir calisma icindeki her dosya/kural bazli olayin (eslesti, degistirildi, atlandi, hata oldu) detayli izi.'
    )
    op.create_table('denetim_uyarilari',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('calisma_id', sa.Integer(), nullable=False, comment='Bu ikincil riskin tespit edildigi maskeleme calismasi.'),
    sa.Column('dosya_yolu', sa.Text(), nullable=False, comment='Riskli bulunan dosyanin goreli yolu.'),
    sa.Column('maskelenmis_icerik', sa.Text(), nullable=False, comment='Karar verilene kadar hedef klasore YAZILMAYAN, maskelenmis dosya icerigi - onay/red sonrasi (dismissed durumunda) buradan hedef klasore serbest birakilir.'),
    sa.Column('kodlama', sa.String(length=50), nullable=True, comment='Serbest birakilirken kullanilacak dosya kodlamasi (orn. utf-8); bilinmiyorsa NULL -> utf-8 varsayilir.'),
    sa.Column('gerekce', sa.Text(), nullable=False, comment="Denetim LLM'inin ikincil risk gerekcesi; denetim basarisiz olduysa hata aciklamasi."),
    sa.Column('denetim_basarisiz_mi', sa.Boolean(), nullable=False, comment='True ise bu kayit bir RISK TESPITI degil, denetim LLM cagrisinin basarisiz/zaman asimina ugramis olmasidir - dogrulama yapilamadigi icin guvenlik geregi yine de karantinaya alinmistir.'),
    sa.Column('durum', sa.String(length=20), nullable=False, comment="'pending', 'confirmed' (risk gercek, dosya karantinada kalir) ya da 'dismissed' (yanlis alarm, dosya hedef klasore serbest birakilir)."),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Kaydin olusturulma zamani.'),
    sa.CheckConstraint("durum IN ('pending', 'confirmed', 'dismissed')", name='ck_audit_warnings_status'),
    sa.ForeignKeyConstraint(['calisma_id'], ['maskeleme_calismalari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="Maskeleme sonrasi, tespit eden LLM'den bagimsiz adversarial denetimden gecen dosyalarin ikincil risk kayitlari - review_queue'dan ayri ve daha kritik; karar verilene kadar ilgili dosya hedef klasore kopyalanmaz."
    )
    op.create_table('gozden_gecirme_kuyrugu',
    sa.Column('id', sa.Integer(), nullable=False, comment='Birincil anahtar.'),
    sa.Column('calisma_id', sa.Integer(), nullable=True, comment='Ilgili maskeleme calismasi; run disi analizlerde NULL olabilir.'),
    sa.Column('dosya_yolu', sa.Text(), nullable=False, comment='Bulguyu iceren dosyanin goreli yolu.'),
    sa.Column('satir_no', sa.Integer(), nullable=True, comment='Bulgunun dosya icindeki 1-tabanli satir numarasi; hesaplanamadiysa NULL.'),
    sa.Column('bulunan_deger', sa.Text(), nullable=True, comment='Modelin supheli buldugu birebir metin degeri.'),
    sa.Column('varlik_tipi', sa.String(length=100), nullable=False, comment='Serbest/dinamik tip adi; enum ile sinirlandirilmaz.'),
    sa.Column('guven_seviyesi', sa.String(length=20), nullable=False, comment="'yuksek', 'orta' ya da 'dusuk'."),
    sa.Column('gerekce', sa.Text(), nullable=True, comment='Modelin neden suphelendigine dair kisa aciklama.'),
    sa.Column('baglam', sa.Text(), nullable=True, comment='Insan incelemesi icin bulgunun yakin cevresi.'),
    sa.Column('durum', sa.String(length=20), nullable=False, comment="'pending', 'approved', 'rejected' ya da 'ignored'."),
    sa.Column('olusturulma_tarihi', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Kaydin olusturulma zamani.'),
    sa.CheckConstraint("durum IN ('pending', 'approved', 'rejected', 'ignored')", name='ck_review_queue_status'),
    sa.CheckConstraint("guven_seviyesi IN ('yuksek', 'orta', 'dusuk')", name='ck_review_queue_confidence'),
    sa.ForeignKeyConstraint(['calisma_id'], ['maskeleme_calismalari.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment="LLM'in dusuk/orta guvenli bulgulari ve LLM tarama hatalari icin insan onayi bekleyen kuyruk."
    )
    # ### end Alembic commands ###

    # ELLE EKLENDI (autogenerate dialect-ozel WHERE kosullu index uretmez):
    # bir baglam_id icin ayni anda EN FAZLA BIR 'mask' tipi 'in_progress'
    # satiri olabilir - eszamanli export yarisini (TOCTOU) veritabani
    # seviyesinde kapatir (bkz. app/services/exporter.py).
    op.create_index(
        "uq_masking_runs_context_in_progress_mask",
        "maskeleme_calismalari",
        ["baglam_id"],
        unique=True,
        sqlite_where=sa.text("durum = 'in_progress' AND islem_tipi = 'mask'"),
    )


def downgrade() -> None:
    op.drop_index("uq_masking_runs_context_in_progress_mask", table_name="maskeleme_calismalari")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gozden_gecirme_kuyrugu')
    op.drop_table('denetim_uyarilari')
    op.drop_table('denetim_kaydi')
    op.drop_table('maskeleme_calismalari')
    op.drop_table('deger_eslemeleri')
    op.drop_table('yer_tutucu_sayaclari')
    op.drop_table('maskeleme_baglamlari')
    op.drop_table('haric_tutma_desenleri')
    op.drop_table('filtre_kurallari')
    op.drop_table('dosya_tipi_kategori_kisitlamasi')
    # ### end Alembic commands ###
